/** @type {import('tailwindcss').Config} */
const lightVars = {
  '--color-primary': '#123456',
  '--color-primary-light': '#234567',
  '--color-primary-dark': '#0F1E2D',
  '--color-secondary': '#345678',
  '--color-secondary-light': '#456789',
  '--color-secondary-dark': '#234567',
  '--color-tertiary': '#56789A',
  '--color-tertiary-light': '#6789AB',
  '--color-tertiary-dark': '#345678',
  '--color-accent': '#F0A500',
  '--color-accent-light': '#FFB732',
  '--color-accent-dark': '#D18E00',

  '--color-neutral-100': '#FFFFFF',
  '--color-neutral-200': '#F5F5F5',
  '--color-neutral-300': '#E0E0E0',
  '--color-neutral-400': '#BDBDBD',
  '--color-neutral-500': '#9E9E9E',
  '--color-neutral-600': '#4B5563',
  '--color-neutral-700': '#374151',
  '--color-neutral-800': '#1F2937',
  '--color-neutral-900': '#212121',

  '--color-green-bg': '#d1fae5',
  '--color-green-text': '#065f46',
  '--color-green-border': '#34d399',
  '--color-green-bg-hover': '#bbf7d0',
  '--color-green-text-hover': '#047857',
  '--color-green-border-hover': '#059669',

  '--color-blue-bg': '#dbeafe',
  '--color-blue-text': '#1e40af',
  '--color-blue-border': '#3b82f6',
  '--color-blue-bg-hover': '#bfdbfe',
  '--color-blue-text-hover': '#2563eb',
  '--color-blue-border-hover': '#2563eb',

  '--color-yellow-bg': '#fef3c7',
  '--color-yellow-text': '#78350f',
  '--color-yellow-border': '#fbbf24',
  '--color-yellow-bg-hover': '#fde68a',
  '--color-yellow-text-hover': '#b45309',
  '--color-yellow-border-hover': '#d97706',

  '--color-red-bg': '#fee2e2',
  '--color-red-text': '#991b1b',
  '--color-red-border': '#f87171',
  '--color-red-bg-hover': '#fecaca',
  '--color-red-text-hover': '#b91c1c',
  '--color-red-border-hover': '#ef4444',

  '--color-purple-bg': '#ede9fe',
  '--color-purple-text': '#6d28d9',
  '--color-purple-border': '#a78bfa',
  '--color-purple-bg-hover': '#ddd6fe',
  '--color-purple-text-hover': '#7c3aed',
  '--color-purple-border-hover': '#8b5cf6',

  '--modal-overlay-bg': 'rgba(15, 23, 42, 0.35)',
  '--modal-bg': 'var(--color-neutral-100)',
  '--modal-title-color': 'var(--color-neutral-700)',
  '--modal-text-color': 'var(--color-neutral-600)',
  '--modal-btn-primary-bg': 'var(--color-red-bg)',
  '--modal-btn-primary-text': 'var(--color-red-text)',
  '--modal-btn-primary-border': 'var(--color-red-border)',
  '--modal-btn-primary-hover-bg': 'var(--color-red-bg-hover)',
  '--modal-btn-primary-hover-text': 'var(--color-red-text-hover)',
  '--modal-btn-primary-hover-border': 'var(--color-red-border-hover)',
  '--modal-btn-secondary-bg': 'var(--color-neutral-100)',
  '--modal-btn-secondary-text': 'var(--color-neutral-700)',
  '--modal-btn-secondary-border': 'var(--color-neutral-300)',
  '--modal-btn-secondary-hover-bg': 'var(--color-neutral-200)',
  '--modal-btn-secondary-hover-text': 'var(--color-neutral-700)',
  '--modal-btn-secondary-hover-border': 'var(--color-neutral-300)',
  '--modal-shadow': '0 10px 25px rgba(0, 0, 0, 0.15)',
};

const darkVars = {
  '--color-primary': '#c5d0db',
  '--color-primary-light': '#2a394a',
  '--color-primary-dark': '#9fb0c2',
  '--color-secondary': '#9fb0c2',
  '--color-secondary-light': '#b4c1cf',
  '--color-secondary-dark': '#7f8fa3',
  '--color-tertiary': '#1f2833',
  '--color-tertiary-light': '#263241',
  '--color-tertiary-dark': '#141b24',
  '--color-accent': '#F0A500',
  '--color-accent-light': '#FFB732',
  '--color-accent-dark': '#D18E00',

  '--color-neutral-100': '#1a222c',
  '--color-neutral-200': '#10161d',
  '--color-neutral-300': '#253140',
  '--color-neutral-400': '#2f3c4d',
  '--color-neutral-500': '#435366',
  '--color-neutral-600': '#8fa0b2',
  '--color-neutral-700': '#b6c2d2',
  '--color-neutral-800': '#d5dde7',
  '--color-neutral-900': '#e7edf3',

  '--color-green-bg': '#123c2f',
  '--color-green-text': '#cfeadf',
  '--color-green-border': '#3aa886',
  '--color-green-bg-hover': '#174737',
  '--color-green-text-hover': '#daf2e8',
  '--color-green-border-hover': '#53bc9a',

  '--color-blue-bg': '#1b2f53',
  '--color-blue-text': '#d3def3',
  '--color-blue-border': '#5a82d1',
  '--color-blue-bg-hover': '#223a63',
  '--color-blue-text-hover': '#dde7f7',
  '--color-blue-border-hover': '#6b92e0',

  '--color-yellow-bg': '#4b2b13',
  '--color-yellow-text': '#f3e5bd',
  '--color-yellow-border': '#d39b40',
  '--color-yellow-bg-hover': '#5a3517',
  '--color-yellow-text-hover': '#f7eccb',
  '--color-yellow-border-hover': '#e2ad58',

  '--color-red-bg': '#4a1f1f',
  '--color-red-text': '#f4d6d6',
  '--color-red-border': '#d66a6a',
  '--color-red-bg-hover': '#5a2626',
  '--color-red-text-hover': '#f7dede',
  '--color-red-border-hover': '#e27b7b',

  '--color-purple-bg': '#3d2c66',
  '--color-purple-text': '#e4def8',
  '--color-purple-border': '#8f74d6',
  '--color-purple-bg-hover': '#473475',
  '--color-purple-text-hover': '#ece7fb',
  '--color-purple-border-hover': '#a187e2',

  '--modal-overlay-bg': 'rgba(2, 6, 23, 0.55)',
  '--modal-bg': 'var(--color-neutral-100)',
  '--modal-title-color': 'var(--color-neutral-800)',
  '--modal-text-color': 'var(--color-neutral-600)',
  '--modal-btn-secondary-bg': 'var(--color-neutral-100)',
  '--modal-btn-secondary-text': 'var(--color-neutral-900)',
  '--modal-btn-secondary-border': 'var(--color-neutral-300)',
  '--modal-btn-secondary-hover-bg': 'var(--color-neutral-200)',
  '--modal-btn-secondary-hover-text': 'var(--color-neutral-900)',
  '--modal-btn-secondary-hover-border': 'var(--color-neutral-300)',
  '--modal-shadow': '0 10px 25px rgba(0, 0, 0, 0.3)',
};

module.exports = {
  content: ['./src/main/resources/templates/**/*.html'],
  darkMode: 'media',
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: 'var(--color-primary)',
          light: 'var(--color-primary-light)',
          dark: 'var(--color-primary-dark)',
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          light: 'var(--color-secondary-light)',
          dark: 'var(--color-secondary-dark)',
        },
        tertiary: {
          DEFAULT: 'var(--color-tertiary)',
          light: 'var(--color-tertiary-light)',
          dark: 'var(--color-tertiary-dark)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          light: 'var(--color-accent-light)',
          dark: 'var(--color-accent-dark)',
        },
        neutral: {
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
        },
        'green-bg': 'var(--color-green-bg)',
        'green-text': 'var(--color-green-text)',
        'green-border': 'var(--color-green-border)',
        'green-bg-hover': 'var(--color-green-bg-hover)',
        'green-text-hover': 'var(--color-green-text-hover)',
        'green-border-hover': 'var(--color-green-border-hover)',
        'blue-bg': 'var(--color-blue-bg)',
        'blue-text': 'var(--color-blue-text)',
        'blue-border': 'var(--color-blue-border)',
        'blue-bg-hover': 'var(--color-blue-bg-hover)',
        'blue-text-hover': 'var(--color-blue-text-hover)',
        'blue-border-hover': 'var(--color-blue-border-hover)',
        'yellow-bg': 'var(--color-yellow-bg)',
        'yellow-text': 'var(--color-yellow-text)',
        'yellow-border': 'var(--color-yellow-border)',
        'yellow-bg-hover': 'var(--color-yellow-bg-hover)',
        'yellow-text-hover': 'var(--color-yellow-text-hover)',
        'yellow-border-hover': 'var(--color-yellow-border-hover)',
        'red-bg': 'var(--color-red-bg)',
        'red-text': 'var(--color-red-text)',
        'red-border': 'var(--color-red-border)',
        'red-bg-hover': 'var(--color-red-bg-hover)',
        'red-text-hover': 'var(--color-red-text-hover)',
        'red-border-hover': 'var(--color-red-border-hover)',
        'purple-bg': 'var(--color-purple-bg)',
        'purple-text': 'var(--color-purple-text)',
        'purple-border': 'var(--color-purple-border)',
        'purple-bg-hover': 'var(--color-purple-bg-hover)',
        'purple-text-hover': 'var(--color-purple-text-hover)',
        'purple-border-hover': 'var(--color-purple-border-hover)',
      },
    },
    screens: {
      sm: '480px', // Mobile
      md: '768px', // Tablet
      lg: '1024px', // Desktop
    },
  },
  plugins: [
    function ({ addBase }) {
      addBase({
        ':root': lightVars,
        '@media (prefers-color-scheme: dark)': {
          ':root': darkVars,
        },
      });
    },
  ],
};
